# Generated by Django 5.0.6 on 2025-03-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10, unique=True)),
                ('contact_method', models.CharField(choices=[('WhatsApp Only', 'WhatsApp Only'), ('Telegram Only', 'Telegram Only'), ('Both', 'Both')], max_length=20)),
                ('receipt_method', models.CharField(choices=[('UPI', 'UPI'), ('Bank', 'Bank')], max_length=10)),
                ('upi_id', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_account', models.CharField(blank=True, max_length=18, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=11, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
