# Generated by Django 5.0.6 on 2025-03-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
