# Generated by Django 5.0.6 on 2025-03-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agent_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='secretAnswer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='secretQuestion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
