# Generated by Django 5.0.6 on 2025-03-14 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_agent_secretanswer_agent_secretquestion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='ifsc_code',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='receipt_method',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='upi_id',
        ),
    ]
