# Generated by Django 5.0.6 on 2025-03-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('contact_method', models.CharField(choices=[('WhatsApp Only', 'WhatsApp Only'), ('Telegram Only', 'Telegram Only'), ('Both', 'Both')], max_length=20)),
                ('pincode', models.CharField(max_length=6)),
                ('total_members', models.IntegerField()),
                ('cover_type', models.CharField(choices=[('Individual', 'Individual'), ('Floater', 'Floater')], max_length=20)),
                ('adults', models.IntegerField()),
                ('children', models.IntegerField()),
                ('agent_id', models.CharField(blank=True, max_length=50, null=True)),
                ('additional_comments', models.TextField(blank=True, null=True)),
                ('unique_id', models.CharField(max_length=20, unique=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
